stages:
  - release

semantic_release:
  stage: release
  image: node:10
  variables:
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/gitlab-config
  script:
    - semantic-release -e @semantic-release/gitlab-config
  only:
    - master