---
image:
  name: hashicorp/terraform:0.12.20
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

variables:
  GOOGLE_APPLICATION_CREDENTIALS: "creds/serviceaccount.json"

before_script:
  - rm -rf .terraform
  - terraform --version
  - cd infra\ -\ GCP/
  - mkdir -p creds
  - echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  - echo "init"

stages:
  - code_review
  - tag_release

code_review:
  stage: code_review
  script:
    - echo "validate"
    - echo "plan"
  only:
    - merge_request

release:
  image: brunosb/semantic-delivery-gitlab:latest
  before_script:
    - git fetch --tags -f
  stage: tag_release
  script:
    - semantic-delivery-gitlab --token $GITLAB_TOKEN
  when: manual
  only:
    - master
