---
image: brunosb/semantic-delivery-gitlab:latest

stages:
  - release

publish:
  stage: release
  script:
    - git fetch --tags -f
    - semantic-delivery-gitlab --token $GITLAB_TOKEN
  only:
    - master
