## nginx configuration
## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
##
controller:
  # kind: DaemonSet
  kind: Deployment
  replicaCount: 1
  config:
    hsts-include-subdomains: "false"
    server-name-hash-bucket-size: "256"
    enable-vts-status: "true"
    use-http2: "false"
    ssl-ciphers: "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4"
    ssl-protocols: "TLSv1.1 TLSv1.2"
    server-tokens: "false"
  hostNetwork: true
  stats:
    enabled: true
  publishService:
    enabled: true
  service:
    externalTrafficPolicy: Local
  metrics:
    serviceMonitor:
      enabled: true
  extraArgs:
    v: 2
    # force-namespace-isolation: ""
  resources:
   requests:
     cpu: 50m
     memory: 75Mi
   limits:
     cpu: 100m
     memory: 200Mi
rbac:
  create: true
serviceAccount:
    create: true
